### ISSUE TITLE
One-hot Goals

### ISSUE THREAD

**Issue by qifang804** [intuitive-robots/beso#5]
Hi authors, recently I was trying to make the one-hot training/inference running, since I found the option of "future/onehot" in the config file. However, errors keep showing up, and it seems that the `trajectory_loader.py` doesn't handle the processing of one-hot goals. Could you shed some light on how to get the onehot training/inference working? Many Thanks!

**Comment by mbreuss** [comment]
Hi, thanks for your interest in our work. I remember testing one-hot once during the beginning of the project in 22. However, I cannot remember what I did different back then. The one-hot stuff is adopted from this codebase https://github.com/jeffacce/play-to-policy My best tipp would be to check our their codebase as I dont have a good idea on that implementation anymore. Otherwise if you can share the error message I can have a look and try to help.
